apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-spring-boot-with-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kotlin-spring-boot-with-nginx
  template:
    metadata:
      labels:
        app: kotlin-spring-boot-with-nginx
    spec:
      containers:
        - name: kotlin-spring-boot-without-nginx-container
          image: hardokkerdokker/hvalfangst:kotlin-spring-boot-with-exposed
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kotlin-spring-boot-with-nginx-service
spec:
  selector:
    app: kotlin-spring-boot-with-nginx
  ports:
    - name: http
      protocol: TCP
      port: 8081 # Nginx targets this port
      targetPort: 8080
  type: LoadBalancer